### PR TITLE
update Readme with steps on how to run

### LINKED ISSUE #531: Add steps, How to run and deploy the project
**Is your feature request related to a problem? Please describe.**
Readme should have steps on how to run the project locally on machine. Preferably, also how to deploy it. 

**Describe the solution you'd like**

Run on staging debug:
- flutter run --dart-define=flavor=qa

Run on production:
- flutter run --dart-define-from-file=.env.prod.json

Deploy to iOS:
- flutter build ipa --release --dart-define-from-file=.env.prod.json

Deploy to Android:
- flutter build appbundle --release --dart-define-from-file=.env.prod.json

where .env.prod.json is the file containing the production environment variables.

```
{
  "flavor": "prod",
  "apiKey": "<FIREBASE_API_KEY>",
  "appIdAndroid": "<FIREBASE_APP_ID>",
  "appIdIos": "<FIREBASE_APP_ID>",
  "messagingSenderId": "<FIREBASE_MESSAGING_SENDER_ID>",
  "projectId": "<FIREBASE_PROJECT_ID>",
  "storageBucket": "<FIREBASE_STORAGE_BUCKET>",
  "iosBundleId": "<IOS_BUNDLE_ID>",
}
```

### PR DESCRIPTION
**Pull request by dhirajchaurasiya**
- [ ]  Fixed #531 
- [ ]  I added the steps to on How to Run and Deploy the Project in README.md

### CODE REVIEW

**Comment by hashirshoaeb** [comment]
Nice. thanks. can you make following changes? 

Make two headings.

(heading) Run project
add bullet points (non numeric)
(heading) Deploy 
add bullet points (non numeric)

**Comment by dhirajchaurasiya** [comment]
Sure I will do that way.

**Comment by hashirshoaeb** [comment]
Should be headings:
```
## Run project

## Deploy

```

**Comment by hashirshoaeb** [comment]
sorry, closed by mistake

**Review by hashirshoaeb — APPROVED** [review]

**Pull request merged**
