### PR TITLE
Adding function to greet user relative to the time.

### PR DESCRIPTION
**Pull request by spiderxm**

### CODE REVIEW

**Comment by hashirshoaeb** [comment]
Tips:
- Mention the issue that you tried to fix in this PR. i.e.(#194)
- Add description with your PR.

**Comment by hashirshoaeb** [comment]
And also request for review.

**Review by hashirshoaeb — APPROVED** [review]

**Comment by hashirshoaeb** [comment]
Can you explain why did you prefer, `TimeOfDay` over `DateTime`?

**Comment by spiderxm** [comment]
I prefer, `TimeOfDay` over `DateTime` because we only need the time to decide the greeting messing so choosing `DateTime` would take more time to find it and would occupy extra space.

**Pull request merged**
