### PR TITLE
I have replaced gesture detectors with Buttons

### PR DESCRIPTION
**Pull request by ShahzadUmarBaig**
I have removed all of the gesture detectors and changed them with Cupertino Buttons to solve the button animations plus I have also removed the gesture detector on homepage and converted that Icon Button with a fixed size, You can check it.

### CODE REVIEW

**Comment by hashirshoaeb** [comment]
@ShahzadUmarBaig Perfect, 
And what about button animations for container we discussed before?

**Comment by ShahzadUmarBaig** [comment]
Which button animations? Do you mean the Arrow button in Mood selector row?

**Comment by hashirshoaeb** [comment]
nope, the gesture detector in mycontainer

**Comment by ShahzadUmarBaig** [comment]
I have now changed the mycontainer file and changed it to button now

**Comment by ShahzadUmarBaig** [comment]
I am closing this PR as I have made some incorrect changes in this PR

**Pull request closed without merging**
