### PR TITLE
UI Splash Screen

### PR DESCRIPTION
**Pull request by AbdullahAhmedSoomro**
- Splash Screen Completed.

which one is better
First one
WhatsApp Image 2023-02-10 at 2 25 01 PM (1)
Second one
WhatsApp Image 2023-02-10 at 2 25 01 PM

### CODE REVIEW

**Comment by hashirshoaeb** [comment]
what is the difference between both?

**Review by hashirshoaeb — APPROVED** [review]

**Comment by AbdullahAhmedSoomro** [comment]
Minor color difference in center

**Comment by hashirshoaeb** [comment]
use any, both are good.

**Comment by AbdullahAhmedSoomro** [comment]
Merged it?

**Pull request merged**
