### PR TITLE
Use root navigator for pop

### LINKED ISSUE #31: Nested routing
On poping the initial route of the inner navigator should take context to the outer navigator.

### PR DESCRIPTION
**Pull request by jordanmlacalle**
Resolves #31 by specifying use of the root navigator for pop method.

### CODE REVIEW

**Comment by hashirshoaeb** [comment]
Thanks. It's woking.

**Comment by hashirshoaeb** [comment]
@jordanmlacalle I will be happy if you can share some blog post or article, so that I can learn more about it.

**Comment by jordanmlacalle** [comment]
@hashirshoaeb I am familiar with it from use in a production app. Other than the Flutter documentation and StackOverflow, I do not have much to share other than my own experience:

https://api.flutter.dev/flutter/widgets/Navigator/of.html
https://stackoverflow.com/a/61653930

**Comment by hashirshoaeb** [comment]
Thank you. ❤️ I appreciate that.
If you don't mind, can i connect with you on social platform, like linkedin or twitter?

**Comment by jordanmlacalle** [comment]
Sure! I'm not very active there yet, but I am happy to connect. I've sent you a connection request.

**Pull request merged**
