### PR TITLE
Added Profile Page

### LINKED ISSUE #75: Add Profile Page
Implement ProfilePage Screen
- [ ] Greetings widget
- [ ] Username widget
- [ ] Stats widget

For reference, check  Screen(2) [link](https://github.com/hashirshoaeb/star_book/blob/master/CONTRIBUTING.md#mock-up)

### PR DESCRIPTION
**Pull request by cyber-venom003**
Fixes #75 . 
Profile Page has been added.
Screenshot_1610609701

### CODE REVIEW

**Comment by cyber-venom003** [comment]
@hashirshoaeb Please check and tell if any more changes are required.

**Comment by hashirshoaeb** [comment]
- Revert the changes for home_page.dart. You can add button for yourself to test the profile page but you do not need to push those changes for PR. 
- Use variable to set name, see User model in models director.
- make a separate widget for stats, in the same file.

Note: you do not  need to close this PR. just made the above changes in the same branch and it will be good to  go.

Also try using cupertino dynamic colors. Not necessary for now. but it will be good for your learning.

**Comment by cyber-venom003** [comment]
Ok sure.

**Comment by cyber-venom003** [comment]
@hashirshoaeb Check for requested changes in latest commit.

**Review by hashirshoaeb — APPROVED** [review]

**Pull request merged**
