### PR TITLE
UI/create calendar

### PR DESCRIPTION
**Pull request by AbdullahAhmedSoomro**
UI Create Calendar

- Calendar Logic Implemented

https://user-images.githubusercontent.com/50518325/215752547-a669be58-25fe-40f5-8570-5e76d293f9ac.mp4

### CODE REVIEW

**Comment by AbdullahAhmedSoomro** [comment]
Calendar UI will be implemented after the completion of issue #292 UI Gradient Scaffold

**Comment by hashirshoaeb** [comment]
Screenshot 2023-02-01 at 11 18 31 PM
use font and spacing through theme

**Comment by hashirshoaeb** [comment]
https://www.figma.com/file/eR9WSsPKudnuIjvHud8REF/Star-Book?node-id=520%3A3507&t=hbLG9m0pdxtjmv6U-0

**Comment by hashirshoaeb** [comment]
only font sizes will be defined by theme, font weights can be copywith.

**Comment by AbdullahAhmedSoomro** [comment]
Implemented font styling and added color in font style using foreground theme, but I think it will create problems in the future,

**Comment by AbdullahAhmedSoomro** [comment]
Implemented font styling and added color in font style using foreground theme, but I think it will create problems in the future,

**Review by hashirshoaeb — APPROVED** [review]

**Pull request merged**
