### PR TITLE
UI/mood tile

### PR DESCRIPTION
**Pull request by AbdullahAhmedSoomro**
UI Mood Tile

- Mood Tile Completed.

- Selected Tile

Screenshot_20230213-183029_1

- Unselected Tile

Screenshot_20230213-183036_1 (1)

### CODE REVIEW

**Comment by AbdullahAhmedSoomro** [comment]
trailing circle size is correct or not. In Figma, the circle size is very large.
Figma UI
image

**Comment by AbdullahAhmedSoomro** [comment]
UI Mood Tile

- Added Opacity when the tile is not selected
- Minor Updates

Screenshot_20230213-190103

**Comment by AbdullahAhmedSoomro** [comment]
@hashirshoaeb approved?

**Comment by hashirshoaeb** [comment]
Yes, you can merge

**Pull request merged**
